### ISSUE TITLE
NullPointerException on login

### ISSUE THREAD

**Issue by marianzange** [bpfoster/openfire-crowd-auth-module#2]
Hi,

first thanks for the great work! Unfortunately, I always get the following exception when trying to login:

java.lang.NullPointerException
    at net.fosterzor.openfire.crowd.admin.CrowdAdminProvider.getAdmins(CrowdAdminProvider.java:56)
    at org.jivesoftware.openfire.admin.AdminManager.loadAdminList(AdminManager.java:138)
    at org.jivesoftware.openfire.admin.AdminManager.isUserAdmin(AdminManager.java:250)
    at org.jivesoftware.openfire.admin.login_jsp._jspService(login_jsp.java:146)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:39)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:74)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:50)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:78)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:164)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:425)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:494)
    at org.eclipse.jetty.server.session.SessionHandler.handle(SessionHandler.java:182)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:933)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:362)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:867)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:245)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:334)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:559)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1007)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:747)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:203)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:406)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:679)

Any ideas?

Thanks!

**Comment by bpfoster** [comment]
Hi Marian, thanks for the report.  I will have a fix for this error shortly, but I am wondering what the root cause is.  Can you verify 3 things for me?
1)  that the system property 'provider.group.className' is set to the CrowdGroupProvider (net.fosterzor.openfire.crowd.group.CrowdGroupProvider)
2)  that there are no previous errors in the logs
3)  that the groups specified by property 'crowdAuth.admin.groups' exist in your Crowd instance?

Thanks so much

**Comment by marianzange** [comment]
Hi,  

Thanks so much for the quick reply. I don’t see any previous errors and I’ve double checked if the group exists
within Crowd and if the system properties are set correctly. Unfortunately I can’t find any additional hint...

Best,
Marian

**Comment by bpfoster** [comment]
Marian,
Feel free to download and try 1.0.2-RC1 (https://github.com/downloads/bpfoster/openfire-crowd-auth-module/openfire-crowd-auth-plugin-1.0.2-RC1.jar), which will no longer give you this error.

However, I still believe there is something else going on with your installation.  From my testing, you will get the exact error message you're seeing if there's some kind of error connecting to Crowd (e.g. bad Crowd URL, bad Crowd application authentication, etc).  These types of things should be logged to the Openfire error log (by default this should be located in ${openfireHome}/logs/error.log).

I would check and verify that you have correctly followed the installation steps 2 & 3 and that crowd.properties has all the correct values to connect to Crowd.

**Comment by bpfoster** [comment]
BTW due to a bug in Openfire 3.7.1 (http://issues.igniterealtime.org/browse/OF-480), the logs I mentioned may not be getting written to.  For me (linux tar.gz build), I had to edit the startup script OPENFIRE_HOME/bin/openfire
Change line 262 _from_:

`nohup "$app_java_home/bin/java" -server -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Dinstall4j.jvmDir="$app_java_home" -Dexe4j.moduleName="$prg_dir/$progname"  $INSTALL4J_ADD_VM_PARAMS -classpath "$local_classpath" com.install4j.runtime.Launcher start org.jivesoftware.openfire.starter.ServerStarter false false "$prg_dir/../logs/stderror.log" "$prg_dir/../logs/stdoutt.log" true true false "" true true 0 0 "" 20 20 "Arial" "0,0,0" 8 500 "version 3.7.1" 20 40 "Arial" "0,0,0" 8 500 -1 -DopenfireHome="$prg_dir/../" -Dopenfire.lib.dir="$app_home/lib" &`

_to_:

`nohup "$app_java_home/bin/java" -server -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Dinstall4j.jvmDir="$app_java_home" -Dexe4j.moduleName="$prg_dir/$progname"  $INSTALL4J_ADD_VM_PARAMS -classpath "$local_classpath" com.install4j.runtime.Launcher start org.jivesoftware.openfire.starter.ServerStarter false false "$prg_dir/../logs/stderror.log" "$prg_dir/../logs/stdoutt.log" true true false "" true true 0 0 "" 20 20 "Arial" "0,0,0" 8 500 "version 3.7.1" 20 40 "Arial" "0,0,0" 8 500 -1 -Dopenfire.lib.dir="$app_home/lib" &`

(Note the change in placement of -DopenfireHome)

**Comment by marianzange** [comment]
Thanks for helping me out! I finally had some time to look into the issue and you were right. It was a communication problem with the Crowd server. First, the root CA from my Crowd server's SSL certificate wasn't in the list of trusted CAs (it should be in there since it's the Geo Trust Global CA). And second, I accidentally sent the request to crowdserver_url/services/rest instead of crowdserver_url/rest

**Comment by bpfoster** [comment]
Thanks for the answer!  I'm going to release 1.0.2 soon, which at the very least will show a proper error message on the admin screen for this. Again, thanks for the feedback and please report any other issues or suggestions you have in the future!
